---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: ryan.blundon@protonmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
          email: ryan.blundon@protonmail.com
        cnameStrategy: Follow
      selector: 
        dnsZones:
          - 'mk-labs.cloud'
          - 'monetnaildesign.com'

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: ryan.blundon@protonmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-issuer-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
          email: ryan.blundon@protonmail.com
        cnameStrategy: Follow
      selector: 
        dnsZones:
          - 'mk-labs.cloud'
          - 'monetnaildesign.com'
