---
apiVersion: v2
name: cert-manager-umbrella
description: A helm chart to include cert-manager with values
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
- name: cert-manager
  version: v1.15.1
  repository: https://charts.jetstack.io
  alias: cert-manager
  condition: cert-manager.enabled
