---
# https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml

cert-manager:
  enabled: false
  installCRDs: true
  dns01RecursiveNameservers: 1.1.1.1:53
  dns01RecursiveNameserversOnly: true
  livenessProbe:
    enabled: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true