
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: router-cert
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  commonName: apps.hub.mk-labs.cloud
  dnsNames:
  - apps.hub.mk-labs.cloud
  - "*.apps.hub.mk-labs.cloud"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: router-cert
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: router-cert
