---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: Keeps track of changes in the application image
  labels:
    app: monetnaildesign-nginx
    template: nginx-example
  name: monetnaildesign-nginx