---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: monetnaildesign-tls
  namespace: monetnaildesign
spec:
  commonName: 'monetnaildesign.com'
  dnsNames:
  - monetnaildesign.com
  - www.monetnaildesign.com
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  renewBefore: 360h0m0s
  secretName: monetnaildesign-tls
  usages:
  - server auth
  - client auth