apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-cluster-token
            key: dopplerToken
            namespace: external-secrets
