---
# Variables for Unbound https://github.com/aruhier/ansible-role-unbound

### Server ###

unbound_chroot: '""'
unbound_num_threads: 2
unbound_interfaces:
  - "{{ ip_address }}"
#unbound_do_ip4: "yes"
unbound_do_ip6: "no"
#unbound_do_udp: "yes"
#unbound_do_tcp: "yes"

# list of strings, as the order impact how policies are interpreted
unbound_outgoing_policies: []

unbound_access_control:
  - '192.168.1.0/24 allow'
  - '192.168.3.0/24 allow'
  - '192.168.5.0/24 allow'
  - '192.168.10.0/24 allow'
  - '10.1.71.0/24 allow'
  
unbound_access_control_tag: []
unbound_access_control_tag_action: []
unbound_access_control_tag_data: []
unbound_access_control_view: []

unbound_private_addresses:
  - '192.168.1.0/24'
  - '192.168.3.0/24'
  - '192.168.5.0/24'
  - '192.168.10.0/24'
  - '10.1.71.0/24'

unbound_private_domains:
  - 'mk-labs.cloud'

unbound_domains_insecure: []
unbound_do_not_query_addresses: []
unbound_local_zones: []
unbound_local_datas: []
unbound_local_data_ptrs: []
unbound_local_zone_tags: []
unbound_local_zone_overrides: []

unbound_trust_anchors: []
unbound_trusted_keys_files: []

### Remote Control ###

unbound_control_enable: "no"
unbound_control_interface: []

### Stub, forward zones and others ###

unbound_rpz_zones: []  # list of dicts
unbound_stub_zones: []  # list of dicts
unbound_forward_zones:
  - name: 'int.mk-labs.cloud'
    forward-addr:
      - '10.1.71.5'
  - name: '.'
    forward-addr:
      - '1.0.0.1@53#one.one.one.one'
      - '1.1.1.1@53#one.one.one.one'

# For stub and forward zones, if a key inside one of the dict is an iterable,
# it will iterate inside it to duplicate the option with all the contained
# values.
# Can be useful in case of multiple forward-addr for a same zone:
#   Example:
#     unbound_forward_zones:
#       - {name: "test.tld", "forward-addr": ["192.0.2.5", "192.0.2.6"]}

unbound_views: []  # list of strings, as options can be multiples