---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials # This is the secret name
  namespace: openshift-lightspeed
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  refreshInterval: "1h"
  data:
    - secretKey: apitoken
      remoteRef:
        key: OPENAI_TOKEN
