---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kubernetes.io/metadata.name: openshift-lightspeed
    name: openshift-lightspeed
    argocd.argoproj.io/managed-by: openshift-gitops-operator
    openshift.io/cluster-monitoring: 'true'
  name: openshift-lightspeed
spec:
  finalizers:
  - kubernetes