# ------------------------------------------------------------------------------
# FILE: roles/traefik/handlers/main.yml
# ------------------------------------------------------------------------------

- name: restart traefik
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_base_dir }}"
    state: restarted
