---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token # This is the secret name
  namespace: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  refreshInterval: "1h"
  data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE_TOKEN
