---
# file: site.yml

- name: Master playbook for home lab
  hosts: all
  gather_facts: false

  tasks:
    - name: Process DNS entries
      when: inventory_hostname == "infra01"
      ansible.builtin.import_tasks:
        file: dns-entry.yml
      tags:
        - update-dns
        - never
