---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monetnaildesign-web
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    name: internal
    namespace: monetnaildesign
  project: default
  source:
    path: applications/app-web-monetnaildesign
    repoURL: https://github.com/rblundon/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas