---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
        argocd.argoproj.io/sync-wave: "1"
  name: image-registry-pvc
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-nfs
