# ------------------------------------------------------------------------------
# FILE: roles/docker-host/handlers/main.yml
# ------------------------------------------------------------------------------

- name: restart docker
  systemd:
    name: docker
    state: restarted
