apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmGlobals:
  chartHome: charts/openshift-console-plugin

helmCharts:
- name: openshift-console-plugin
  version: 0.3.0
  repo: https://gnunn-gitops.github.io/helm-charts
  valuesFile: values.yaml
  namespace: dev-console-plugin
  releaseName: dev-console-plugin
