# ------------------------------------------------------------------------------
# FILE: roles/common/handlers/main.yml
# ------------------------------------------------------------------------------

- name: restart timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
