# ------------------------------------------------------------------------------
# FILE: roles/common/handlers/main.yml
# ------------------------------------------------------------------------------

- name: restart chrony
  systemd:
    name: chrony
    state: restarted

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
