# ------------------------------------------------------------------------------
# FILE: roles/common/handlers/main.yml
# ------------------------------------------------------------------------------

- name: restart chrony
  systemd:
    name: chrony
    state: restarted
