apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oidc-token-refresher
  namespace: openshift-pipelines
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - patch
  - update
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-token-refresher
  namespace: openshift-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oidc-token-refresher
subjects:
- kind: ServiceAccount
  name: oidc-token-refresher
  namespace: openshift-pipelines
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-token-refresher
  namespace: openshift-pipelines
