---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: open-cluster-management
    name: open-cluster-management
    argocd.argoproj.io/managed-by: openshift-gitops-operator
  name: open-cluster-management
spec:
  finalizers:
  - kubernetes
