---
# Kubernetes Prerequisites Role Defaults

# Kubernetes version to install (should be overridden in group_vars)
kubernetes_version: "v1.33"

# CNI plugin to install
cni_plugin: "calico"

# SELinux configuration
selinux_state: "permissive"

# Kernel modules to load
required_kernel_modules:
  - overlay
  - br_netfilter

# Sysctl parameters for Kubernetes
k8s_sysctl_params:
  - "net.bridge.bridge-nf-call-iptables = 1"
  - "net.bridge.bridge-nf-call-ip6tables = 1"
  - "net.ipv4.ip_forward = 1"

containerd_dependencies:
  - curl
  - gnupg2
  - software-properties-common
  - apt-transport-https
  - ca-certificates

kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl
