apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-wol-service
  labels:
    kubernetes.io/os: linux
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
      - enabled: true
        name: wol@<interface>.service
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,W1VuaXRdCkRlc2NyaXB0aW9uPVdha2Utb24tTEFOIGZvciAlaQpSZXF1aXJlcz1uZXR3b3JrLnRhcmdldApBZnRlcj1uZXR3b3JrLnRhcmdldAoKW1NlcnZpY2VdCkV4ZWNTdGFydD0vdXNyL3NiaW4vZXRodG9vbCAtcyAlaSB3b2wgZwpUeXBlPW9uZXNob3QKCltJbnN0YWxsXQpXYW50ZWRCeT1tdWx0aS11c2VyLnRhcmdldA==
        mode: 0644
        overwrite: true
        path: /etc/systemd/system/wol@.service
