---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets (internal)
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: internal
    namespace: openshift-operators
  project: default
  source:
    path: cluster/external-secrets/overlays/internal
    repoURL: https://github.com/rblundon/homelab.git
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
