apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: openshift-gitops
spec:
  generators:
    - clusters: {} # Automatically use all clusters defined within Argo CD
    # - list:
    #     elements:
    #       - cluster: dev
    #         url: https://kubernetes-dev.example.com
    #       - cluster: prod
    #         url: https://kubernetes-prod.example.com
  template:
    metadata:
      name: '{{cluster}}-external-secrets'
    spec:
      project: apps
      source:
        repoURL: 'https://github.com/rblundon/homelab.git'
        targetRevision: HEAD
        path: 'cluster/external-secrets/overlays/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - RespectIgnoreDifferences=true
        - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas