---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nfs-storage
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {} # Variable is .name
  template:
    metadata:
      name: '{{.name}}-nfs-storage'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      destination:
        name: '{{.name}}'
        namespace: openshift-nfs-storage
      project: default
      source:
        path: cluster/nfs-storage
        repoURL: https://github.com/rblundon/homelab.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - RespectIgnoreDifferences=true
        - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas