---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nmstate
  namespace: openshift-nmstate
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: openshift-nmstate
  project: default
  source:
    path: cluster/nmstate/overlays/hub
    repoURL: https://github.com/rblundon/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
  