---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lightspeed-operator
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          name: "internal"
  template:
    metadata:
      name: '{{.name}}-openshift-lightspeed'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      source:
        repoURL: https://github.com/rblundon/homelab.git
        targetRevision: HEAD
        path: cluster/openshift-lightspeed-operator/overlays/{{.name}}
      destination:
        name: '{{.name}}'
        namespace: openshift-lightspeed
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - RespectIgnoreDifferences=true
        - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
