---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: synology-csi
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {} # Variable is .name
  template:
    metadata:
      name: '{{.name}}-synology-csi'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      spec:
        destination:
          name: '{{.name}}'
          namespace: synology-csi
        project: default
        source:
          path: cluster/synology-storageclass
          repoURL: https://github.com/rblundon/homelab.git
          targetRevision: HEAD
        syncPolicy:
          automated:
            prune: false
            selfHeal: true
          syncOptions:
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
          managedNamespaceMetadata:
            labels:
              argocd.argoproj.io/managed-by: openshift-gitops
        ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
          - /spec/replicas