apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-admin
  namespace: dev-tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: sonarqube-admin
  data:
    - secretKey: password
      remoteRef:
        key: SONARQUBE_ADMIN_PASSWORD
