---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-system
    name: istio-system
    argocd.argoproj.io/managed-by: openshift-gitops-operator
  name: istio-system
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-cni
    name: istio-cni
    argocd.argoproj.io/managed-by: openshift-gitops-operator
  name: istio-cni
spec:
  finalizers:
  - kubernetes