---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator3
  namespace: openshift-operators
spec:
  channel:  candidates
  installPlanApproval: Automatic #Manual
  name: servicemeshoperator3
  source: redhat-operators
  sourceNamespace: openshift-marketplace