apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-pipeline-scc-rolebinding
  namespace: product-catalog-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole
subjects:
- kind: ServiceAccount
  name: github-pipeline
