---
- name: Master playbook to create VM from a template
  hosts: all
  gather_facts: false

- name: Proxmox Clone Ubuntu VM Playbook
  ansible.builtin.import_playbook: proxmox_clone_ubuntu_vm.yml
  when: vm_os_distribution == "ubuntu" and platform == "proxmox"

- name: Proxmox Clone Fedora VM Playbook
  ansible.builtin.import_playbook: proxmox_clone_fedora_vm.yml
  when: vm_os_distribution == "fedora" and platform == "proxmox"

# - name: DNS Playbook
#   ansible.builtin.import_playbook: add_dns_entry.yml

# - name: DHCP Playbook
#   ansible.builtin.import_playbook: add_dhcp_entry.yml

- name: Start VM Playbook
  ansible.builtin.import_playbook: proxmox_start_vm.yml

- name: Set Hostname Playbook
  ansible.builtin.import_playbook: set_hostname.yml
