---
- name: Set hostname of VM
  hosts: all
  gather_facts: false

  tasks:
    - name: Set hostname of VM
      become: true
      delegate_to: "{{ inventory_hostname }}"
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: Set timezone to US/Central
      become: true
      community.general.timezone:
        name: US/Central
