---
- name: Dnsmasq
  hosts: localhost
  become: yes
  vars:
    - additional_dhcp_hosts:
        ethernet_switch:
          desc: "SNO Hub Cluster"
          mac: 98:b7:85:1e:c6:f1
          ip: 10.1.71.10

  roles:
    - role: ricsanfre.dnsmasq