---
- name: Install all software on infra01
  hosts: infra01
  gather_facts: true
  become: true

  tasks:
  # - Update all packages
  # - Install ansible-core
  # - Copy .vault_pass.txt from laptop and set env variable
  # - Clone git repo
  # - Install ansible required packages

    - name: Install ansible-core
      ansible.builtin.package:
        name: ansible-core
        state: present
      become: true

    - name: Install dnf-plugins-core
      ansible.builtin.package:
        name: dnf-plugins-core
        state: present
      become: true

    - name: Register status of /usr/local/bin/terraform
      ansible.builtin.stat:
        path: /usr/local/bin/terraform
      register: terraform_path

    - name: Download and installt erraform version
      when: not terraform_path.stat.exists
      block:
        - name: Download  and install terraform
          ansible.builtin.unarchive:
            src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
            dest: "/usr/local/bin/"
            remote_src: true
            mode: '0755'
            exclude: "LICENSE.txt"

  roles:
    - somaz94.ansible_k8s_iac_tool.install_kustomize
