---
- name: Install all software on infra01
  hosts: infra01
  gather_facts: true
  become: true

  collections:
    - somaz94.ansible_k8s_iac_tool

  tasks:
  # - Update all packages
  # - Install ansible-core
  # - Copy .vault_pass.txt from laptop and set env variable
  # - Clone git repo
  # - Install ansible required packages

    - name: Install ansible-core
      ansible.builtin.package:
        name: ansible-core
        state: present
      become: true

    - name: Install dnf-plugins-core
      ansible.builtin.package:
        name: dnf-plugins-core
        state: present
      become: true

    - name: Download terraform
      ansible.builtin.get_url:
        url: https://releases.hashicorp.com/terraform/terraform_{{ terraform_version }}/terraform_{{ terraform_version }}_{{ ansible_facts.ansible_os_family }}_{{ ansible_facts.ansible_architecture }}.zip
        dest: /tmp/terraform.zip
        mode: 0755

    - name: Install terraform
      ansible.builtin.package:
        name: terraform
        state: present
      become: true

  roles:
    - install_kustomize
      
