---
- name: Run all tasks necessary to configure matchbox to install the cluster
  hosts: matchbox
  connection: local
  gather_facts: true

  tasks:
    - name: Deploy DNS entries for cluster via Terraform
      community.general.terraform:
        project_path: 01-dns/
        variables:
          freeipa_password: "{{ vault_freeipa_password }}"
        state: present
        force_init: true

    - name: Deploy DHCP entries for cluster via Terraform
      ansible.builtin.include_tasks:
        file: 02-dhcp/ip-reservations.yml

    - name: OpenShift Installer install-config.yaml
      ansible.builtin.template:
        src: 03-openshift-image/templates/install-config.yaml.j2
        dest: 03-openshift-image/install-config.yaml
        mode: '0644'

    - name: OpenShift Installer agent-config.yaml
      ansible.builtin.template:
        src: 03-openshift-image/templates/agent-config.yaml.j2
        dest: 03-openshift-image/agent-config.yaml
        mode: '0644'

    - name: Create OpenShift image
      ansible.builtin.include_tasks:
        file: 03-openshift-image/create-openshift-image.yml

    - name: Move PXE assets to matchbox
      ansible.builtin.include_tasks:
        file: 03-openshift-image/move-pxe-assets.yml

    - name: Terraform matchbox groups file
      ansible.builtin.template:
        src: 04-matchbox/templates/groups.tf.j2
        dest: 04-matchbox/groups.tf
        mode: '0644'

    - name: Terraform matchbox profiles file
      ansible.builtin.template:
        src: 04-matchbox/templates/profiles.tf.j2
        dest: 04-matchbox/profiles.tf
        mode: '0644'

    - name: Terraform matchbox provider file
      ansible.builtin.template:
        src: 04-matchbox/templates/provider.tf.j2
        dest: 04-matchbox/provider.tf
        mode: '0644'

    - name: Configure Matchbox via Terraform
      community.general.terraform:
        project_path: 04-matchbox/
        state: present
        force_init: true
