---
- name: Run all tasks necessary to configure matchbox to install the cluster
  hosts: 127.0.0.1
  connection: local
  gather_facts: true
  include_vars: vars.yml

  tasks:
    - name: Deploy DNS entries for cluster via Terraform
      community.general.terraform:
        project_path: 01-dns/
        variables:
          freeipa_password: "{{ freeipa_password }}"
        state: present
        force_init: true

    - ansible.builtin.include_tasks:
        file: 02-dhcp/ip-reservations.yml
        include_vars: vars.yml
