---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: storage-network-int-worker01
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  nodeSelector:
    kubernetes.io/hostname: int-worker01
  desiredState:
    interfaces:
      - name: enp2s0f0.121
        state: up
        type: vlan
        vlan:
          base-iface: enp2s0f0
          id: 121
      - bridge:
          port:
            - name: enp2s0f0.121
        ipv4:
          address:
            - ip: 10.10.121.64
              prefix-length: 24
          enabled: true
        name: storage-network
        state: up
        type: linux-bridge
        description: Linux bridge with enp1s0 as a port on VLAN 121

---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: storage-network-int-worker02
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  nodeSelector:
    kubernetes.io/hostname: int-worker02
  desiredState:
    interfaces:
      - name: enp2s0f0.121
        state: up
        type: vlan
        vlan:
          base-iface: enp2s0f0
          id: 121
      - bridge:
          port:
            - name: enp2s0f0.121
        ipv4:
          address:
            - ip: 10.10.121.65
              prefix-length: 24
          enabled: true
        name: storage-network
        state: up
        type: linux-bridge
        description: Linux bridge with enp1s0 as a port on VLAN 121