apiVersion: v1
baseDomain: int.mk-labs.cloud
compute:
- name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
metadata:
  name: hub
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14  #<== Internal node network. Not available externally.
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.1.71.0/24  #<== Real world host network.
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16  #<== Internal cluster overlay. Not available externally.
platform:
  baremetal:
    apiVIPs:
    - 10.1.71.11
    ingressVIPs:
    - 10.1.71.12
fips: false
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfY2ZlYjYxMjE5ZmFiNDA1OWIwZWZmZDJlZTUxZTNlOTc6UjhaUEs2UEQyTjlBNURERUxHUjE0UDdLQ1pWR1ZPME1KUDYzUTUzQ0hBMTlIVjE4STJETzBHMkdGNzg2QjQxOA==","email":"rblundon@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfY2ZlYjYxMjE5ZmFiNDA1OWIwZWZmZDJlZTUxZTNlOTc6UjhaUEs2UEQyTjlBNURERUxHUjE0UDdLQ1pWR1ZPME1KUDYzUTUzQ0hBMTlIVjE4STJETzBHMkdGNzg2QjQxOA==","email":"rblundon@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTk0ZGM3NWFiLTEyYzAtNGRhMC1hMjI5LTBmOTZiY2Y2NGZhMDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhabVppWWpRMFpqWXlPVEkwTVRKaFlqWTBaVFl3T1RSaFpqRmpabUk0WlNKOS5tS3RLNnYxa1ZEZjZOcXJweTBXTjRubEQ1bDFhTG9sbWtvV3YzYzcwdTJJb29iODBsZGEtanJHYV85LWVVUU1IM1dsU3BvdEQzQzFBdi1wUE5pT0tKM2paSGJGOEoxTlNtSmdsb0hSR214NDZXb2FGYlh5c2JuUVhwamNBU0l4MnpZQ1hFSWlaNkZrRzFwUUMzWHlISTdsMVh6dEZ1TG5yWFBGUUhUdHFJcm5KNDA5R2c2Uk5jNXhnOEpMWEY4UmFWM2x1SGZqdWY2RHJRaGdzc3Vla1BOcDc0Q0g1Y0k4T3pYVWVLMy1xelZkQ3FaSDhZYXp5dHVJRDFmQkxyUDV4Nnh5a3U3NFd6dEJXaE9rMFRBdnVldkNHSVlLOV91MGlFSVl0bll5TTJndnpWSTl4YXBUckkwMW9DcF9NXzh2YU1YVzJjb2ZUNEE5b2VrZDM0ZmdkUGs4MFU0UzBBN0RabWpiMFZCT211Y0xuX1F6U2FQMkZjMmtGNDExenBfb2I5ZHl1MEZhSXN5bF9YTG5kZDF3S21JU2N6N04tZDBpM244QkpvYnh6YUJwZzJxUEdhV2VvTXJNWmYwRGdzVEo4VmhBSWlBNTVwUDYwSGVpRzdzMUhUQ1Rudl9kTlpaMWY0TzMwUTBNVnRTQWl6Q3Q0azdnbHd5VzZVamU4czd2WVZPekFvUEFvTEZKQVZVcUcwWUNUYXJodnBsZ204MWlzWHhwWk5nMEQwUkZISmRIYXFmRXQtVE5wVHplZzlBOEZ6QkVQaG5ZTU1ZMEhzUVpONHFNbE1kTHBHOHJrZU04azRoWGIyQ08wcFZvMUluY1d2aFQ5cDgxV1M0QlNfMHR6bG1EckdTbXJYN3JNTnN1V2RZbmlpNm16WFJuRUlIV25FelNUc2hhLUtRcw==","email":"rblundon@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTk0ZGM3NWFiLTEyYzAtNGRhMC1hMjI5LTBmOTZiY2Y2NGZhMDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhabVppWWpRMFpqWXlPVEkwTVRKaFlqWTBaVFl3T1RSaFpqRmpabUk0WlNKOS5tS3RLNnYxa1ZEZjZOcXJweTBXTjRubEQ1bDFhTG9sbWtvV3YzYzcwdTJJb29iODBsZGEtanJHYV85LWVVUU1IM1dsU3BvdEQzQzFBdi1wUE5pT0tKM2paSGJGOEoxTlNtSmdsb0hSR214NDZXb2FGYlh5c2JuUVhwamNBU0l4MnpZQ1hFSWlaNkZrRzFwUUMzWHlISTdsMVh6dEZ1TG5yWFBGUUhUdHFJcm5KNDA5R2c2Uk5jNXhnOEpMWEY4UmFWM2x1SGZqdWY2RHJRaGdzc3Vla1BOcDc0Q0g1Y0k4T3pYVWVLMy1xelZkQ3FaSDhZYXp5dHVJRDFmQkxyUDV4Nnh5a3U3NFd6dEJXaE9rMFRBdnVldkNHSVlLOV91MGlFSVl0bll5TTJndnpWSTl4YXBUckkwMW9DcF9NXzh2YU1YVzJjb2ZUNEE5b2VrZDM0ZmdkUGs4MFU0UzBBN0RabWpiMFZCT211Y0xuX1F6U2FQMkZjMmtGNDExenBfb2I5ZHl1MEZhSXN5bF9YTG5kZDF3S21JU2N6N04tZDBpM244QkpvYnh6YUJwZzJxUEdhV2VvTXJNWmYwRGdzVEo4VmhBSWlBNTVwUDYwSGVpRzdzMUhUQ1Rudl9kTlpaMWY0TzMwUTBNVnRTQWl6Q3Q0azdnbHd5VzZVamU4czd2WVZPekFvUEFvTEZKQVZVcUcwWUNUYXJodnBsZ204MWlzWHhwWk5nMEQwUkZISmRIYXFmRXQtVE5wVHplZzlBOEZ6QkVQaG5ZTU1ZMEhzUVpONHFNbE1kTHBHOHJrZU04azRoWGIyQ08wcFZvMUluY1d2aFQ5cDgxV1M0QlNfMHR6bG1EckdTbXJYN3JNTnN1V2RZbmlpNm16WFJuRUlIV25FelNUc2hhLUtRcw==","email":"rblundon@redhat.com"}}}'
sshKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICB/UfNTK2JX8Lq0H75yHrWgr32vhLFBcE7r+cEC6hvd rblundon@rblundon-mac'
