apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: admission-tls
  namespace: stackrox
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: doppler-push-secret
      kind: ClusterSecretStore
  selector:
    secret:
      name: admission-control-tls
  data:
    - match:
        secretKey: ca.pem
        remoteRef:
          remoteKey: ACS_ADMISSION_CONTROL_TLS_CA
    - match:
        secretKey: admission-control-cert.pem
        remoteRef:
          remoteKey: ACS_ADMISSION_CONTROL_TLS_CERT
    - match:
        secretKey: admission-control-key.pem
        remoteRef:
          remoteKey: ACS_ADMISSION_CONTROL_TLS_KEY
