apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: collector-tls
  namespace: stackrox
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: doppler-push-secret
      kind: ClusterSecretStore
  selector:
    secret:
      name: collector-tls
  data:
    - match:
        secretKey: ca.pem
        remoteRef:
          remoteKey: ACS_COLLECTOR_TLS_CA
    - match:
        secretKey: collector-cert.pem
        remoteRef:
          remoteKey: ACS_COLLECTOR_TLS_CERT
    - match:
        secretKey: collector-key.pem
        remoteRef:
          remoteKey: ACS_COLLECTOR_TLS_KEY
