global:
    scrape_interval: 15s

scrape_configs:
    - job_name: prometheus
      scrape_interval: 30s
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: node-exporter
      scrape_interval: 30s
      static_configs:
          - targets:
                ["192.168.0.1:9100", "192.168.0.10:9100", "192.168.0.11:9100"]

    - job_name: cadvisor
      scrape_interval: 30s
      static_configs:
          - targets: ["192.168.0.1:9101", "192.168.0.11:9101"]

rule_files:
    - prometheus_alerts_rules.yml

alerting:
    alertmanagers:
        - static_configs:
              - targets:
                    - 192.168.0.1:9093
