---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: keycloak-operator
spec:
  channel: fast
  installPlanApproval: Automatic #Manual
  name: keycloak-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
