# ------------------------------------------------------------------------------
# FILE: roles/fastpass_workers/tasks/main.yml
# ------------------------------------------------------------------------------
- name: Generate join command for worker nodes
  ansible.builtin.command: kubeadm token create --print-join-command
  delegate_to: "{{ groups['fastpass_control_plane'][0] }}"
  run_once: true
  register: worker_join_command

- name: Join worker nodes to the cluster
  ansible.builtin.command: "{{ hostvars[groups['fastpass_control_plane'][0]].worker_join_command.stdout }}"

- name: Label and Taint on-stage worker nodes
  become: false
  ansible.builtin.command: "kubectl {{ item }}"
  delegate_to: localhost
  run_once: true
  loop:
    - label node seven-dwarfs-mine-train zone=on-stage --overwrite
    - taint node seven-dwarfs-mine-train dedicated=external:NoSchedule --overwrite
  when: "'seven-dwarfs-mine-train' in inventory_hostname"

- name: Label backstage worker node haunted-mansion
  become: false
  ansible.builtin.command: "kubectl label node haunted-mansion zone=backstage --overwrite"
  delegate_to: localhost
  run_once: true
  when: "'haunted-mansion' in inventory_hostname"

- name: Label backstage worker node peter-pans-flight
  become: false
  ansible.builtin.command: "kubectl label node peter-pans-flight zone=backstage --overwrite"
  delegate_to: localhost
  run_once: true
  when: "'peter-pans-flight' in inventory_hostname"
