http:
  routers:
    nextcloud:
      rule: "Host(`nextcloud.local.mk-labs.cloud`) || Host(`the-grid.local.mk-labs.cloud`) || Host(`the-grid.mk-labs.cloud`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - nextcloud-caldav
      service: nextcloud

  middlewares:
    nextcloud-caldav:
      redirectRegex:
        permanent: true
        regex: "https://(.*)/.well-known/(card|cal)dav"
        replacement: "https://${1}/remote.php/dav/"

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://10.1.71.128:80"
