apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: external-monitor-reader
  name: external-monitor-reader
  namespace: openshift-monitoring
type: kubernetes.io/service-account-token
