# file: inventory.yml
proxmox:
  hosts:
    main-street-usa:
      ansible_host: 10.1.71.11
      ansible_user: wed
      ansible_become: true
    tomorrowland:
    fantasyland:

magic_kingdom:
  hosts:
    main-street-usa:
    tomorrowland:
    fantasyland:

dns_server:
  hosts:
    monorail:

ntp_servers:
  hosts:
    sundial:
    
load_balancers:
  hosts:
    lightning_lane:
      ansible_host: 10.1.71.35
      ansible_become: true

step_ca_server:
  hosts:
    turnstile:
      ansible_host: 10.1.71.34
      ansible_become: true

authentik_server:
  hosts:
    guest-relations:
      ansible_host: 10.1.71.40
      ansible_become: true

prometheus_server:
  hosts:
    cinderella-castle:

prometheus_nodes:
  hosts:
    cinderella-castle:

# node_explorer:
#   hosts:
#     cinderella-castle:

# alertmanager:
#   hosts:
#     cinderella-castle:

# grafana:
#   hosts:
#     cinderella-castle:

papermc_server:
# ansible-galaxy role install engonzal.papermc
  hosts:
    arcade:

semaphore_server:
  hosts:
    imagineering:

n8n_server:
  hosts:
    tiki-room:

# dhcp_server:
#   hosts:
#     matchbox:

backup_servers:
  hosts:
    timekeeper:

# ipaserver:
#   hosts:
#     infra01.int.mk-labs.cloud:

# matchbox_server:
#   hosts:
#     matchbox:

terraform_server:
  hosts:
    infra01:
