{{- if and .Values.le.prod.enabled .Values.le.apiCert.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: okd-api
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dnsNames:
  - api.{{ .Values.cluster_name }}.{{ .Values.base_domain }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: okd-api
---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names:
      - api.{{ .Values.cluster_name }}.{{ .Values.base_domain }}
      servingCertificate:
        name: okd-api
{{- end }}
