---
- name: Master playbook to create VM from a template
  hosts: all
  gather_facts: false

- name: DNS Playbook
  ansible.builtin.import_playbook: add_dns_entry.yml

  # Create DHCP Reservation

- name: Proxmox Clone VM Playbook
  ansible.builtin.import_playbook: proxmox_clone_vm.yml
# - name: Set Hostname Playbook
#   ansible.builtin.import_playbook: set_hostname.yml
