- name: Install Observability stack (targets)
  hosts: target
  tags:
      - monitoring
      - target
  roles:
      - ../roles/target

- name: Install Observability stack (observer)
  hosts: observer
  tags:
      - monitoring
      - observer
  roles:
      - ../roles/observer
