kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - https://github.com/redhat-cop/gitops-catalog/cost-management-operator/overlays/aggregate

patchesJson6902:
  - path: patch-source-and-name.yaml
    target:
      group: koku-metrics-cfg.openshift.io
      kind: KokuMetricsConfig
      name: instance
      version: v1beta1
