---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: synology-csi
    name: synology-csi
    argocd.argoproj.io/managed-by: openshift-gitops-operator
  name: synology-csi
spec:
  finalizers:
  - kubernetes
