---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "1"
  labels:
    kubernetes.io/metadata.name: synology-csi
    name: synology-csi
    argocd.argoproj.io/managed-by: openshift-gitops-operator
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: baseline
  name: synology-csi
spec:
  finalizers:
  - kubernetes
