apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
# if all params are empty, synology CSI will choose an available location to create volume
parameters:
  dsm: '10.10.121.35'
  protocol: 'iscsi'
  location: '/volume1'
  csi.storage.k8s.io/fstype: 'ext4'
reclaimPolicy: Delete #Retain
allowVolumeExpansion: true
