---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: client-info-secret
  namespace: synology-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  refreshInterval: "1h"
  data:
    - secretKey: client-info.yml
      remoteRef:
        key: SYNOLOGY_CLIENT_INFO
