---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: metallb-system
    name: metallb-system
    argocd.argoproj.io/managed-by: openshift-gitops-operator
    openshift.io/cluster-monitoring: 'true'
  name: metallb-system
spec:
  finalizers:
  - kubernetes