---
# ansible/roles/haproxy/handlers/main.yml

- name: Reload haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
  listen: reload haproxy

- name: Restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    daemon_reload: true
  listen: restart haproxy

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  listen: restart rsyslog
