---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- namespace.yaml
# Operator deployment
- subscription.yaml
# Deploy cluster resources
- scc.yaml
- pvcs.yaml
