---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kubernetes.io/metadata.name: nginx-ingress
    name: nginx-ingress
    argocd.argoproj.io/managed-by: openshift-gitops-operator
  name: nginx-ingress
spec:
  finalizers:
  - kubernetes
