---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-cache
  namespace: nginx-ingress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-nfs
