apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-wildcard
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  secretName: openshift-wildcard-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.${SUB_DOMAIN}'
  dnsNames:
  - '*.${SUB_DOMAIN}'
