---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  generation: 1
  name: letsencrypt
  namespace: openshift-ingress
spec:
  commonName: '*.apps.hub.int.mk-labs.cloud'
  dnsNames:
  - '*.apps.hub.int.mk-labs.cloud'
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  renewBefore: 360h0m0s
  secretName: letsencrypt
  usages:
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: letsencrypt
  namespace: openshift-config
spec:
  commonName: 'api.hub.int.mk-labs.cloud'
  dnsNames:
  - api.hub.int.mk-labs.cloud
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  renewBefore: 360h0m0s
  secretName: letsencrypt
  usages:
  - server auth
  - client auth