---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: opencost
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops-operator
    kubernetes.io/metadata.name: opencost
    openshift.io/cluster-monitoring: 'true'
spec:
  finalizers:
  - kubernetes
