---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    name: in-cluster
    namespace: opencost
  project: default
  source:
#    path: opencost/opencost/develop/kubernetes/opencost.yaml
#    repoURL: https://raw.githubusercontent.com/
    path: cluster-applications/opencost
    repoURL: git@github.com:rblundon/MK-Labs.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas