---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-cache-external
  namespace: nginx-ingress-external
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-cache-internal
  namespace: nginx-ingress-internal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-nfs
